### ISSUE TITLE
Problem with Bryan, Plume and Robert cases in the provided examples

### ISSUE THREAD

**Issue by Kairzhan** [chengcli/canoe#114]
During testing the capabilities of Canoe, unfortunately, we’ve faced some problems while running some of the examples provided by the code. For example, in Bryan, Plume, Robert cases we always get this error: 

```
ValueError thrown by IndexMap:
RuntimeError: Expect 0.000000 but get 1.000000 for variable Number of vapors.
```

Manual tampering with variables NVAPOR and NCLOUD from index_map.cpp and through cmake/parameters.cmake leads to constant segmentation faults. 

The code was compiled using:

```
mkdir build
cd bulid
cmake .. -DMPI=1 -DNETCDF=1 -DPNETCDF=1
make -j 4
```

Both Linux (Debian 12) and MacOS compiled code produce the same error message.

Could you please provide any suggestions to resolve this issues

**Comment by chengcli** [comment]
Hi Kairzhan,

To compile the case with vapors, such as the **bryan** case or the **plume** test case, you would need to specify the number of vapors. The preset parameters for the **bryan** case are stored in `cmake/bryan.cmake`

You can use the preset parameters by:

```
mkdir build
cd build
cmake .. -DTASK=bryan
make -j 4
```

Similarly, the preset parameters for the **robert** case are stored in `cmake/robert.cmake`.

The preset parmaters for the **plume** case do not exist because the **plume** case is still under development.

Cheng

**Comment by Kairzhan** [comment]
Thanks, that resolved **Bryan** case.
